const READ_CORE = "READ_CORE"
const WRITE_CORE = "WRITE_CORE"
const EXECUTE_CORE = "EXECUTE_CORE"

const READ_NATIVE = "READ_NATIVE"
const WRITE_NATIVE = "WRITE_NATIVE"
const EXECUTE_NATIVE = "EXECUTE_NATIVE"

const READ_ELECTRUM = "READ_ELECTRUM"
const WRITE_ELECTRUM = "WRITE_ELECTRUM"
const EXECUTE_ELECTRUM = "EXECUTE_ELECTRUM"

const READ_ETH = "READ_ETH"
const WRITE_ETH = "WRITE_ETH"
const EXECUTE_ETH = "EXECUTE_ETH"

const READ_WALLET = "READ_WALLET"
const WRITE_WALLET = "WRITE_WALLET"
const EXECUTE_WALLET = "EXECUTE_WALLET"

const READ_SENSITIVE = "READ_SENSITIVE"
const WRITE_SENSITIVE = "WRITE_SENSITIVE"
const EXECUTE_SENSITIVE = "EXECUTE_SENSITIVE"

const READ_PLUGINS = "READ_PLUGINS"
const WRITE_PLUGINS = "WRITE_PLUGINS"
const EXECUTE_PLUGINS = "EXECUTE_PLUGINS"

const READ_FS = "READ_FS"
const WRITE_FS = "WRITE_FS"
const EXECUTE_FS = "EXECUTE_FS"

const READ_UTILITIES = "READ_UTILITIES"
const WRITE_UTILITIES = "WRITE_UTILITIES"
const EXECUTE_UTILITIES = "EXECUTE_UTILITIES"

const READ_SYSDATA = "READ_SYSDATA"
const WRITE_SYSDATA = "WRITE_SYSDATA"
const EXECUTE_SYSDATA = "EXECUTE_SYSDATA"

const SIGN = "SIGN"

module.exports = {
  READ_CORE,
  WRITE_CORE,
  EXECUTE_CORE,

  READ_NATIVE,
  WRITE_NATIVE,
  EXECUTE_NATIVE,

  READ_ELECTRUM,
  WRITE_ELECTRUM,
  EXECUTE_ELECTRUM,

  READ_ETH,
  WRITE_ETH,
  EXECUTE_ETH,

  READ_WALLET,
  WRITE_WALLET,
  EXECUTE_WALLET,

  READ_SENSITIVE,
  WRITE_SENSITIVE,
  EXECUTE_SENSITIVE,

  READ_PLUGINS,
  WRITE_PLUGINS,
  EXECUTE_PLUGINS,

  READ_FS,
  WRITE_FS,
  EXECUTE_FS,

  READ_UTILITIES,
  WRITE_UTILITIES,
  EXECUTE_UTILITIES,

  READ_SYSDATA,
  WRITE_SYSDATA,
  EXECUTE_SYSDATA,

  SIGN,
}

