const allowedOrigins = [
  // Non-Explorer Origins
  "wiki.veruscoin.io",
  "verus.io",
  "discord.gg",
  "github.com",

  // Explorer Origins

  'www.kmdexplorer.io',
  'explorer.veruscoin.io',
  "testex.verus.io",

  // KMD asset chains
  'explorer.dionpay.com',
  'live.block.koinon.cloud',
  'explorer1.patenttx.com',
  'zilla.explorer.dexstats.info',
  'mgnx.explorer.dexstats.info',
  'ccl.explorer.dexstats.info',
  'pirate.explorer.dexstats.info',
  'kv.kmdexplorer.io',
  'explorer.utrum.io',
  'chain.blocnation.io',
  'explorer.chainmakers.co',
  'glx.info',
  'explorer.prlpay.com',
  'pgt.komodo.build/',
  'mshark.kmdexplorer.io',
  'revs.kmdexplorer.io',
  'supernet.kmdexplorer.io',
  'dex.kmdexplorer.io',
  'pangea.kmdexplorer.io',
  'jumblr.kmdexplorer.io',
  'bet.kmdexplorer.io',
  'crypto.kmdexplorer.io',
  'hodl.kmdexplorer.io',
  'explorer.ilien.io',
  'SHARK.explorer.supernet.org',
  'bots.kmdexplorer.io',
  'mgw.kmdexplorer.io',
  'wlc.kmdexplorer.io',
  'explorer.chips.cash',
  'explorer.coqui.cash',
  '178.62.240.191',
  'btch.kmdexplorer.io',
  'blockchain.info',
  'explorer.myhush.org',
  'pizza.komodochainz.info',
  'beer.kmdexplorer.io',
  'ninja.kmdexplorer.io',
  'dsec.kmdexplorer.io',
  'kmdice.explorer.dexstats.info',
  'ksb.explorer.dexstats.info',
  'our.explorer.dexstats.info',
  'rick.kmd.dev',
  'morty.kmd.dev',
  'vote2019.world',
  'http://explorer.marmara.io',
  'zexo.explorer.dexstats.info',
  'labs.explorer.dexstats.info',
  'dp.explorer.komodo.top',
  'wlc21.explorer.dexstats.info/',

  // non-kmd coins
  'explorer.qtum.org',
  'denarius.name',
  'etherscan.io/tx/',
  'live.blockcypher.com/ltc/tx/',
  'live.blockcypher.com/doge/tx/',
  'live.blockcypher.com/dash/tx/',
  'bchain.info/MONA',
  'explorer.viacoin.org',
  'explorer.vertcoin.info',
  'namecha.in',
  'digiexplorer.info',
  'ex.crownlab.eu',
  'explorer.artbyte.me',
  'blockexplorer.gamecredits.com/transactions/',
  'explorer.machinecoin.org',
  'mainnet.iop.cash',
  'btgexplorer.com',
  'bitcoincash.blockexplorer.com',
  'explorer.zclmine.pro',
  'explorer.snowgem.org/',
  'myriadexplorer.com',
  'explorer.bitcore.cc',
  'explorer.bitcoinz.site',
  'www.fuzzbawls.pw/explore/HOdlcoin/tx.php?tx=',
  'suqaexplorer.com',
  'chain.sibcoin.net/en/tx/',
  'explorer.zcha.in/transactions/',
  'explorer.coinpayments.net/transaction.php?chain=4&hash=',
  'prohashing.com/explorer/Argentum/',
  'chain.fair.to/transaction?transaction=',
  'explorer.craveproject.net',
  'explorer.feathercoin.com',
  'guldenchain.com',
  'www.presstab.pw/phpexplorer/PIVX/tx.php?tx=',
  'chainz.cryptoid.info/dmd/search.dws?q=',
  'chainz.cryptoid.info/efl/search.dws?q=',
  'chainz.cryptoid.info/bsd/search.dws?q=',
  'chainz.cryptoid.info/erc/search.dws?q=',
  'chainz.cryptoid.info/sys/search.dws?q=',
  'chainz.cryptoid.info/emc2/search.dws?q=',
  'chainz.cryptoid.info/ixc/search.dws?q=',
  'chainz.cryptoid.info/dgc/search.dws?q=',
  'chainz.cryptoid.info/xmy/search.dws?q=',
  'chainz.cryptoid.info/mue/search.dws?q=',
  'chainz.cryptoid.info/uno/search.dws?q=',
  'groestlsight.groestlcoin.org',
  '206.189.74.116:3001',
  'insight.auroracoin.is',
  'explorer.lbry.io',
  'explorer.getadcoin.com:5000',
  'vivo.explorerz.top:3003',
  'explorer.gobyte.network:5001',
  'explorer.fujicoin.org',
  'explorer.mylinx.io/?',
  'explorer.canadaecoin.ca',
  'explorer.flashcoin.io',
  'explorer.zcoin.io',
  'block.monacocoin.net:8080/tx/',
  'straks.info/transaction/',
  'explorer3.smartcash.cc/tx/',
  'explorer.our-rapture.com/tx/',
  '54.38.145.192:8080/tx/',
  'explorer.polispay.org/tx/',
  'usa.pacblockexplorer.com:3002/tx/',
  'minexexplorer.com/?r=explorer/tx&hash=',
  'be.cleanblockchain.org/tx/',
  'live.reddcoin.com',
  '35.204.174.237:3001/insight/tx/',
  'etherscan.io/tx/',
  'ropsten.etherscan.io/tx/',
]
 
function generateOpenExternalSafe(shell, url) {
  return async (inputUrl) => {
    const URL = url.parse(inputUrl);

    if (URL.protocol === 'https:' && allowedOrigins.includes(URL.host)) {
      shell.openExternal(inputUrl)
      return 0
    } else {
      return -1
    }
  }
}

module.exports = generateOpenExternalSafe